### ISSUE TITLE
Can't Install the package 

### ISSUE THREAD

**Issue by hsk-kr** [Anchor-Protocol/anchor.js#13]
I tried to install the package.

```
npm i @anchor-protocol/anchor.js
```

then I encountered messages.

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@anchor-protocol%2fanchor.js - Not found
npm ERR! 404
npm ERR! 404  '@anchor-protocol/anchor.js@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

When I access the package in npmjs.com, they ask me to login.
But even I logged in , there is a message '404 not found'.

How can I install the anchor.js package
Or Is it not possible yet? do I have to wait for v1.x version?

**Comment by kjessec** [comment]
Not sure why it went to private, it's set to public now. Thanks
