### ISSUE TITLE
How should I call a function 'getBorrowedValue'?

### ISSUE THREAD

**Issue by hsk-kr** [Anchor-Protocol/anchor.js#14]
```typescript
import { LCDClient } from '@terra-money/terra.js';
import {
  Anchor,
  columbus4,
  AddressProviderFromJson,
  MARKET_DENOMS,
} from '@anchor-protocol/anchor.js';

const walletAddress = '[my wallet address]';

const main = async () => {
  const addressProvider = new AddressProviderFromJson(columbus4);
  const lcd = new LCDClient({
    URL: 'https://lcd.terra.dev',
    chainID: 'columbus-4',
  });

  const anchor = new Anchor(lcd, addressProvider);

  try {
    const price = await anchor.anchorToken.getANCPrice();

    const borrowedValue = await anchor.borrow.getBorrowedValue(
      MARKET_DENOMS.UUSD,
      walletAddress
    );

    console.log('price', price);
    console.log('borrowedValue', borrowedValue);
  } catch (err) {
    console.error(err);
  }
};

main();

```

The method getANCPrice works well. but 
Calling a method 'getBorrowedValue' occurs an error.

```
contract query failed: parsing moneymarket::market::QueryMsg: unknown variant `loan_amount`, expected one of `config`, `state`, `epoch_state`, `borrower_info`, `borrower_infos`
```

I think I might've called in a wrong way. but I don't know why it doesn't work.
How should I call this function? (I don't want to use a mnemonic)

**Comment by hsk-kr** [comment]
+ I want to get a LTV ratio of an address. how to get the LTV ratio?

**Comment by kjessec** [comment]
- it seems that there is a schema mismatch - will fix soon.
- LTV ratio as in your borrowed value and borrow limit? will add a function that returns your `current borrow limit`. then you can divide this value with the result of `collateral_value`

**Comment by hsk-kr** [comment]
> * it seems that there is a schema mismatch - will fix soon.
> * LTV ratio as in your borrowed value and borrow limit? will add a function that returns your `current borrow limit`. then you can divide this value with the result of `collateral_value`

Thank you :)

**Comment by kjessec** [comment]
@hsk-kr should be good now. can you try `1.0.0-rc.2`? I also added `getBorrowLimit`

**Comment by hsk-kr** [comment]
The functions work perfectly now. Thank you for your work.

But there is still an error when calls a method 'getCollateralValue'.
Sorry, I didn't mention about this function.

**code**
```javascript
const collateralValue = await anchor.borrow.getCollateralValue(
  MARKET_DENOMS.UUSD,
  walletAddress
 );

console.log(collateralValue);
```

**error**
```
...
data: {
  error: 'contract query failed: parsing cw20_base::msg::QueryMsg: unknown variant `borrower`, expected one of `balance`, `token_info`, `minter`, `allowance`, `all_allowances`, `all_accounts`'
}
...

**Comment by kjessec** [comment]
@hsk-kr my bad -- the function has been fixed and published as rc.3. Could you try? I will go through every single methods tomorrow to make sure 100% acceptance, before releasing `1.0.0`.

Many Thanks

**Comment by hsk-kr** [comment]
Now It works.
Thanks for your prompt reply.
I'm gonna close this issue.

**Comment by kjessec** [comment]
@hsk-kr we are preparing for real `1.0.0`, however the function signatures changed a little. All facade methods will take `Option` object, so it may be a little different in how you use it -- please be prepared to make the changes once we actually publish it. Sorry for the confusion, but I believe it is a necessary update.
