### ISSUE TITLE
Transaction Fee

### ISSUE THREAD

**Issue by oozman** [Anchor-Protocol/anchor.js#18]
Hi,

How or where can I get the transaction fee value?
Like here:
<img width="662" alt="Screen Shot 2021-04-07 at 2 26 52 AM" src="https://user-images.githubusercontent.com/2807969/113760593-f93e9600-9748-11eb-9eb4-e7ab588c5cc0.png">

Thanks

**Comment by kjessec** [comment]
Tx Fee is gas + transaction tax for stablecoin transfers. In webapp, we're using a fixed gas price and tax is calculated on the fly. In anchor.js this is not included as it's ultimately upto the user to determine what Tx Fee to use.

- Tax = `min(transfer_amount * tax_rate, tax_cap)`
- Gas = estimated

tax_rate = https://lcd.terra.dev/treasury/tax_rate
tax_cap = https://lcd.terra.dev/treasury/tax_cap/uusd
