### ISSUE TITLE
Documentation error. Incorrect package name

### ISSUE THREAD

**Issue by caherrerapa** [Anchor-Protocol/anchor.js#19]
https://docs.anchorprotocol.com/developers-terra/anchor-cli has an incorrect package name:
`$ npm install -g @anchor-protocol/cli`

The npm package page has the correct package:
`$ npm install -g @anchor-protocol/anchorcli`

I didn't find in this repo the docs, if you can point me to the repo location I can send a PR

**Comment by kjessec** [comment]
fixed, thanks!
