### ISSUE TITLE
Best way to get aUST price in UST?

### ISSUE THREAD

**Issue by kallama** [Anchor-Protocol/anchor.js#32]
I've noticed that [https://api.extraterrestrial.money/v1/api/prices](https://api.extraterrestrial.money/v1/api/prices) and Mirror have slightly different rates for aUST (as of right now as I type this 1.092843 vs 1.105404.)

Is it possible to calculate how much 1 aUST is in UST using anchor.js or terra.js, and if so, what's the best way?

**Comment by DanKorob** [comment]
Hi @kallama,
You can get the exact aUST rate from _epoch-state_ of _market_ query: [check the code here](https://github.com/Anchor-Protocol/anchor.js/blob/a4b3da7282cfc0e670af44978fda9505b5833dcd/src/queries/money-market/market-epoch-state.ts#L17).
The response will the following:
`{
  exchange_rate: '1.109077188911329171',
  aterra_supply: '1378289453951152'
}`
`exchange_rate` is what you are looking for.
