### ISSUE TITLE
@terra-money/terra.js should be listed as a peer dependency

### ISSUE THREAD

**Issue by jkhaui** [Anchor-Protocol/anchor.js#42]
The terra.js SDK is currently listed as both a [dependency](https://github.com/Anchor-Protocol/anchor.js/blob/5d6dcf50306c91674c0a0c62368d29ac5778b153/package.json#L32) and [dev dependency](https://github.com/Anchor-Protocol/anchor.js/blob/5d6dcf50306c91674c0a0c62368d29ac5778b153/package.json#L37).

I believe it should only be listed as a peer dependency, given that consumers of anchor.js are instructed to install terra.js with anchor.js. If developers are using a different version of terra.js this will likely cause conflicts and difficult to debug issues.

**Comment by MSNTCS** [comment]
Thanks for sharing this, we are waiting for terra.js to release version 2.1.x. and we will reflect this. @cosullivan, please reflect this on PR #41.
